import './globals.css'

import React from 'react'
import { Inter } from 'next/font/google'
import Link from 'next/link'

import ClientWrapper from '@/components/Wrappers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ClientWrapper>
                    <nav>
                        <Link href="/">Home</Link>
                        <Link href="/repos">Repos</Link>
                        <Link href="/login">Login</Link>
                    </nav>
                    {children}
                </ClientWrapper>
            </body>
        </html>
    )
}
